# services:
#   redis-gudbaseball:
#       image: redis:7
#       container_name: redis-gudbaseball
#       ports:
#         - "6380:6379"
#   gudbaseball-backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5005:5005"
#     env_file:
#       - .env
#     volumes:
#       - gudbaseball-logs:/app/winston
#       - /app/node_modules
#       - .:/app
#     depends_on:
#       -  redis-gudbaseball

# volumes:
#   gudbaseball-logs:
    

# docker-compose.yml
services:
  redis-gudbaseball:
    image: redis:7
    container_name: redis-gudbaseball
    ports:
      - "3385:6379"  # Changed to 3385
    networks:
      - gudbaseball-network
  
  gudbaseball-backend:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - gudbaseball-logs:/app/winston
      - /app/node_modules
      - .:/app
    depends_on:
      - redis-gudbaseball
    environment:
      - AI_SERVICE_URL=http://localhost:8001
      - REDIS_URL=redis://localhost:3385  # Changed to 3385

networks:
  gudbaseball-network:
    driver: bridge

volumes:
  gudbaseball-logs: