# services:
#   redis-gudbaseball:
#       image: redis:7
#       container_name: redis-gudbaseball
#       ports:
#         - "6380:6379"
#   gudbaseball-backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5005:5005"
#     env_file:
#       - .env
#     volumes:
#       - gudbaseball-logs:/app/winston
#       - /app/node_modules
#       - .:/app
#     depends_on:
#       -  redis-gudbaseball

# volumes:
#   gudbaseball-logs:
    


services:
  redis-gudbaseball:
    image: redis:7
    container_name: redis-gudbaseball
    ports:
      - "6380:6379"
    networks:
      - gudbaseball-network

  gudbaseball-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    env_file:
      - .env
    volumes:
      - gudbaseball-logs:/app/winston
      - /app/node_modules
      - .:/app
    depends_on:
      - redis-gudbaseball
    networks:
      - gudbaseball-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows access to host
    environment:
      - AI_SERVICE_URL=http://host.docker.internal:8001

networks:
  gudbaseball-network:
    driver: bridge

volumes:
  gudbaseball-logs: